export const HomeTypes = {
    //home
    GET_LISTINGS_START : 'GET_LISTINGS_START',
    GET_LISTINGS_SUCCESS : 'GET_LISTINGS_SUCCESS',
    GET_LISTINGS_FAIL : 'GET_LISTINGS_FAIL',
    GET_LATEST_SUCCESS : 'GET_LATEST_LISTINGS_SUCCESS',
    GET_PLATINUM_SUCCESS : 'GET_LATEST_PLATINUM_SUCCESS',
    GET_URGENT_SUCCESS : 'GET_LATEST_URGENT_SUCCESS',
    GET_SEARCH_RESULT_SUCCESS : 'GET_SEARCH_RESULT_SUCCESS',
    GET_SEARCH_RESULT_FILTER_SUCCESS : 'GET_SEARCH_RESULT_FILTER_SUCCESS',
    GET_URGENT_LISTINGS_FILTER_SUCCESS : 'GET_URGENT_LISTINGS_FILTER_SUCCESS',
    GET_PLAT_LISTINGS_FILTER_SUCCESS : 'GET_PLAT_LISTINGS_FILTER_SUCCESS',
    GET_SIMILAR_SUCCESS : 'GET_SIMILAR_SUCCESS',
    GET_AUTO_DETAILS_SUCCESS : 'GET_AUTO_DETAILS_SUCCESS',
    RESET_LISTS : 'RESET_LISTS',
    // tags
    ADD_TAG : 'ADD_TAG',
    REMOVE_TAG : 'REMOVE_TAG',
    RESET_TAGS : 'RESET_TAGS',
    GET_MODELS : 'GET_MODELS',
    GET_POPULAR_MODELS : 'GET_POPULAR_MODELS',
    GET_FILTER_COUNT : 'GET_FILTER_COUNT',
}
