export const PublicTypes = {
    // public
    TOGGLE_SEARCHBAR : 'TOGGLE_SEARCHBAR',
    TOGGLE_SEARCHBAR_BACKDROP : 'TOGGLE_SEARCHBAR_BACKDROP',
    SET_LOADER : 'SET_LOADER',
    SET_SCROLL : 'SET_SCROLL',
    SET_SCREEN : 'SET_SCREEN',
    SET_NOTIFICATION_COUNT : 'SET_NOTIFICATION_COUNT',
}
